### PR TITLE
OS X doesn't ship with fc-cache - adding install instructions

### PR DESCRIPTION
**Pull request by iandundas**

### CODE REVIEW

**Comment by adam-paterson** [comment]
Are you sure fc-cache is available through brew? I can't see it listed.

I have fc-cache because xquarts requires it, but I'm still struggling to get the fonts working 

http://sht.tl/ucatCC

**Comment by iandundas** [comment]
I installed it via `brew install fontconfig`, which got it working for me

**Comment by iandundas** [comment]
shit I didn't even put that in my pull request. damn. Supposed to be `brew install fontconfig`.

**Comment by adam-paterson** [comment]
Haha, whoops. Thanks! seems to have worked for me too

**Comment by gabrielelana** [comment]
Thanks :+1:

**Pull request merged**
